### ISSUE TITLE
Proposition1.3.2の diam(G)<=2rad(G)

### ISSUE THREAD

**Issue by Kazuuuuuki** [Kazuuuuuki/graph-theory#1]
diam(G)<=2rad(G)が示せない

**Comment by kengohirata** [comment]
x, y を d(x, y) = diam(G) を満たすようにとって、v をグラフの中心としたときに、
d(x, y) <= d(x, v) + d(v, y)
<= 2 rad(G)

ちなみにこの d は距離の公理を満たしています。なぜなら、x, y, v \in V を取ったときに、
P_1: 最短のx-v path (長さ a)
P_2: 最短のy-v path (長さ b)
とすると、P_1 \cup P_2 は長さa+bのx-y walkになるので、最短のx-y pathは長さはa+b 以下になるからです。

**Comment by Kazuuuuuki** [comment]
理解しました！
ありがとう
